### ISSUE TITLE
Zlib error

### ISSUE THREAD

**Issue by pittst3r** [thefrontside/bigtest#557] opened 2020-09-22 19:53 UTC
When running tests with `bigtest ci` we are seeing the following error. It happens with more frequency on CI than locally. All the tests pass, and then during shutdown it seems like we are getting this error.

```
[orchestrator] running!
[orchestrator] launch agents via: http://localhost:34001/__bigtest/index.html?connectTo=ws%3A%2F%2Flocalhost%3A34002
[orchestrator] show GraphQL dashboard via: http://localhost:34000
......[orchestrator] shutting down!
Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (zlib.js:180:17) {
  errno: -5,
  code: 'Z_BUF_ERROR'
}
error Command failed with exit code 255.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 255
Command: /opt/hostedtoolcache/node/14.3.0/x64/bin/node
Arguments: /usr/share/yarn/lib/cli.js test
info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
Directory: /home/runner/work/trade/trade/web/dashboard
Output:

error Command failed with exit code 255.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "test:dashboard" exited with 255.
```

**Comment by cowboyd** [comment] 2020-09-23 02:12
Interesting. We’re using zlib in the proxy server. I wonder if there is some asset that is stuck being served and when the app server shuts down in barfs somehow

**Comment by cowboyd** [comment] 2020-09-29 18:30
It'd be really nice to ensure what's going on, but in the mean time, we probably ought to ensure that we always shut down the proxy server _before_ we shut down the app.

**Comment by chuckcarpenter** [comment] 2020-09-30 20:00
I was able to reproduce with the server running, then refreshing the browser a number of times, and finally running tests. On the 8th refresh, this happened. 

```
[orchestrator] starting
[connection] connected chrome.headless
[orchestrator] running!
[orchestrator] launch agents via: http://localhost:34001/__bigtest/index.html?connectTo=ws%3A%2F%2Flocalhost%3A34002
[orchestrator] show GraphQL dashboard via: http://localhost:34000
[connection] connected agent.1
[connection] connected agent.2
[connection] connected agent.3
[connection] connected agent.4
[connection] connected agent.5
[connection] connected agent.6
[connection] connected agent.7
[connection] connected agent.8
[orchestrator] shutting down!
Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (zlib.js:180:17) {
  errno: -5,
  code: 'Z_BUF_ERROR'
}
```

**Comment by cowboyd** [comment] 2020-10-14 14:50
@pittst3r @chuckcarpenter I've found the cause of this problem. It's whenever a test completes _before_ the app html is finished loading. The browser may cancel the request which causes the output stream of the proxy server to shutdown, and it looks like our streaming chain is not closing properly. So in the case of a test that loads the app and doesn't actually need to use the DOM, it will cause a crash. This probably explains why you've been seeing it less often: the tests actually fully load the DOM.

**Closed as completed** 2020-10-23 15:02 UTC
Labels: 🐛bug
